### ISSUE TITLE
[BE] (가이드모드) 선택한 태그들을 바탕으로 견적을 추천해준다.

### ISSUE THREAD

**Issue by SEONMl** [softeerbootcamp-2nd/H3-UmochaRacer#123]
## 🤖 title
가이드 모드에서 선택한 태그들을 바탕으로 AI 추천 알고리즘을 돌려 견적을 추천해준다.

### 쿼리
- [ ] 성능 response body 프론트와 상의하기
  - id로 자동차 부품 정보 단일 조회 하는 api 구현
- [ ] 서비스 레이어 인터페이스 생성
  - 주말에 각자 쿼리 짜서 구현해오기 위함
- [ ] 코드 리뷰 및 성능 최적화

### 알고리즘
- [ ] ML을 수행한 결과를 얻는다.
- [ ] 치밀한 판매 데이터 셋을 준비한다.
- [ ] 사용자가 선택한 태그를 바탕으로 견적을 추천해준다.

## ⏰ 예상 소요 기간
6H
- 추천 알고리즘 완성 소요 시간에 따라 Sprint 4로 미뤄질 수 있음

**Comment by jjy0709** [comment]
치밀한....데이터셋...
