### ISSUE TITLE
[BE] CI/CD 아키텍처 설정

### ISSUE THREAD

**Issue by SEONMl** [softeerbootcamp-2nd/H3-UmochaRacer#13]
## 🤖 title
CI/CD 아키텍처 선택과 집중과 설정 및 구현

## 💭 detail  
- [x] 도커 사용 중인데 다시 생각해볼 것
- [x] CI/CD 개념 공부
- [x] CI/CD 툴 공부하기
- [x] CI/CD 결정하기 (아마 주말까지 해야 됨)
- [x] 스프린트1까지 자동 배포 환경 설정하는 게 목표

## reference (optional)
[젠킨스 참고](https://seongwon.dev/DevOps/20220715-CICD%EA%B5%AC%EC%B6%95%EA%B8%B01/)
다른 팀 참조할래용 ㅋㅋ

## ⏰ 예상 소요 기간
4H

**Comment by jjy0709** [comment]
reference
https://velog.io/@mminjg/Github-Actions-CodeDeploy%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%9C-EC2-%EB%B0%B0%ED%8F%AC-%EC%9E%90%EB%8F%99%ED%99%94
https://ljlm0402.netlify.app/project/github-action/2/

**Comment by jjy0709** [comment]
자동 배포 완성!!!!!!!! 이제 실제 서비스에는 적용만 하면 됩니당
