### ISSUE TITLE
[BE] Api 호출 오류

### ISSUE THREAD

**Issue by westofsky** [softeerbootcamp-2nd/H3-UmochaRacer#135]
## 🤖 title
Api 호출 오류
## 🚨 bug
- [ ] 일부 데이터 이미지가 제대로 로딩되지 않는 현상
![image](https://github.com/softeerbootcamp-2nd/H3-UmochaRacer/assets/15906101/afbb5821-e3dc-4af9-b094-dac2b5c7fdbf)

**Comment by jjy0709** [comment]
db 저장 시 image source(url) 길이에 제한을 둬서 생긴 오류입니다. 현재 수정하여 반영하였습니다.
<img width="876" alt="image" src="https://github.com/softeerbootcamp-2nd/H3-UmochaRacer/assets/48046928/93f8bc45-70d0-4111-b531-ee36e4b89e25">
