### ISSUE TITLE
[BE] API 데이터 오류

### ISSUE THREAD

**Issue by westofsky** [softeerbootcamp-2nd/H3-UmochaRacer#148]
## 🤖 title
API 데이터 오류
## 🚨 bug
- [x] 파워트레인 이미지가 작아요..
- [x] 바디타입 이미지가 작아요 ..
- [x] 외장색상 마지막 데이터(로버스트 에메랄드 펄)의 imageSrc가 없엉요...

**Comment by jjy0709** [comment]
바디타입 7인승 이미지가 고화질이 없어서 구하고 있어요....
