### ISSUE TITLE
[BE] S3 세팅하기

### ISSUE THREAD

**Issue by SEONMl** [softeerbootcamp-2nd/H3-UmochaRacer#16]
## 🤖 title
S3 세팅하기

## 💭 detail  
- [x] S3 버킷 생성
- [x] 객체(파일) 네이밍 규칙 정하기
- [x] 디렉토리 컨.벤.션 (네이밍, 관리 규칙 정하기)
- [x] 버킷에 사진 객체(파일) 업로드;
- [ ] 접근 권한 결정하기 -> 위험을 감수하고 public으로 열 것인가???

## ⏰ 예상 소요 기간
1.5H

**Comment by jjy0709** [comment]
옵션들은 파일 이름을 한글로 올려서 바꿔야 할 것 같아요.

**Comment by jjy0709** [comment]
Access 관리 같은 경우에는 현재 public으로 해두었는데 찾아보니까 presigned url로 backend에서 권한에 따라 url 설정해줄 수 있을 것 같고 프론트 엔드도 EC2에 배포해둘 경우에는 EC2에서 접근하도록 해서 private으로 두고 할 수 있을 것 같아요.
