### ISSUE TITLE
[BE] ERD 설계하기

### ISSUE THREAD

**Issue by SEONMl** [softeerbootcamp-2nd/H3-UmochaRacer#7]
## 🤖 title
데이터베이스 ERD 설계

## 💭 detail  
- [  ]
- [  ]

**Comment by jjy0709** [comment]
v1.0 완성

**Comment by jjy0709** [comment]
![ERDver1 0](https://github.com/softeerbootcamp-2nd/H3-UmochaRacer/assets/48046928/bfa47ba5-9d17-4274-a0bc-5ad8bcd2be56)
